default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: pg
  # port: 8080
  username: postgres
  password: example

development:
  <<: *default
  database: rails-api-db-developnet

production:
  <<: *default
  database: rails-api-db-production

test:
  <<: *default
  database: rails-api-db-test